### PR TITLE
Add libvirt installation for MacOS.

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by nanliu** [comment]
Fix #25.

**Comment by sandlbn** [comment]
On Mac OS it will require few more steps to monitor VM from Parallels or VMWare. This step will be enough to run only unit tests. On the most of the Linux distribution libvirt package have dependency on qemu and it is possible to run and monitor VM after 1 step. I think this should be included also in README or at last note that libvirt on MacOS needs to be configured to monitor any VM.

**Comment by nanliu** [comment]
@sandlbn do you have an example, or a link we can refer to in the doc?

**Comment by sandlbn** [comment]
@nanliu I think it's good to have this line and we don't need to provide full example, it depends of user requirements. LGTM.

**Pull request merged**
