### PR TITLE
Added support for dynamic metrics #26

### PR DESCRIPTION
**Pull request by sandlbn**
- added support for snap framework dynamic metric 
- travis env updated to the version 1.7 of golang

### CODE REVIEW

**Comment by jcooklin** [comment]
@sandlbn did you intend to checkin the vendor directory?

**Comment by sandlbn** [comment]
@jcooklin Thanks, vendors removed.

**Comment by katarzyna-z** [comment]
In the readme and in the code I see that plugin exposes also this kind of metrics:

```
/libvirt/{domain_name}/disk/{device_name}/wrreq
/libvirt/{domain_name}/net/{interface_name}/rxerrs
```
so consider adding also those dynamic metrics:

```
/libvirt/*/disk/{device_name}/wrreq
/libvirt/*/net/{interface_name}/rxerrs.
```

It seems that {interface_name}, {vcpu_nr}, and {device_name} can be also exposed in namespace as dynamic parts. What do you think?

**Comment by sandlbn** [comment]
@katarzyna-z this will be part of my major refactoring #28 . I have mostly all of code which should be pushed next week. This is just a fix to make a plugin loadable.

**Comment by katarzyna-z** [comment]
@sandlbn OK, it can be done later. LGTM

**Pull request merged**
