### PR TITLE
Updated documentation and example

### PR DESCRIPTION
**Pull request by marcin-krolik**
Updated documentation and example

Summary of changes:
- updated links
- updated documentation
- capitalized Snap

@intelsdi-x/plugin-maintainers

### CODE REVIEW

**Comment by sandlbn** [comment]
@marcin-krolik can we merge that after my PR #36  ? I will work on it tomorrow

**Comment by marcin-krolik** [comment]
@sandlbn not problem

**Comment by sandlbn** [comment]
@marcin-krolik can you delete example from your PR ?

**Comment by marcin-krolik** [comment]
@sandlbn example removed

**Comment by sandlbn** [comment]
LGTM

**Pull request merged**
