### PR TITLE
Updated dependencies for release with updated lib-go

### PR DESCRIPTION
**Pull request by kdembler**

### CODE REVIEW

**Comment by kdembler** [comment]
Failed tests due to bad travis config. Resolved in #54

**Comment by kjlyon** [comment]
Small tests are still failing for this PR. Did #54 not address this problem fully? We may need to open another issue to address this. 
@danieldn

**Comment by danieldn** [comment]
Small test failed because this PR uses travis config that specifies go 1.6, which we no longer support. #54 updates config to run tests on 1.7 and above.

**Comment by kjlyon** [comment]
Thanks @danieldn , @kdembler will you please update your PR to address this.

**Comment by kdembler** [comment]
@kjlyon  Fixed now :)

**Pull request merged**
